# Generated by Django 2.0.3 on 2018-04-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_card_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='list',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
